<?php
/** @package Safebase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SafHumanMap.php");

/**
 * SafHumanDAO provides object-oriented access to the saf_human table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Safebase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SafHumanDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Ci;

	/** @var string */
	public $Name;

	/** @var string */
	public $BloodType;

	/** @var int */
	public $PhoneNumber;

	/** @var int */
	public $Enabled;



}
?>