<?php
/** @package Safebase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SafReportMap.php");

/**
 * SafReportDAO provides object-oriented access to the saf_report table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Safebase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SafReportDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $FkTrabajador;

	/** @var date */
	public $Date;

	/** @var time */
	public $Time;

	/** @var string */
	public $Description;

	/** @var float */
	public $Latitude;

	/** @var float */
	public $Longitude;

	/** @var int */
	public $ReportType;

	/** @var int */
	public $Enabled;



}
?>